### ISSUE TITLE
NegativeValue

### ISSUE THREAD

**Issue by skeith** [keanemind/Keane-Cogs#13]
On this line https://github.com/keanemind/Keane-Cogs/blob/a931ea9e84a5da34d305446680d56cb2b6d6d536/steal/steal.py#L416

Sometimes I encountered an error of NegativeValue, because the player bank balance is not enough and it will stall pilfer (won't go back to main menu) and stuck until reloaded. I have added a try except on my copy and it works well. 

Any thoughts?

**Comment by keanemind** [comment]
Thank you for pointing this out! I double checked my math and there is a mistake on this line, inside the `if` statement: https://github.com/keanemind/Keane-Cogs/blob/a931ea9e84a5da34d305446680d56cb2b6d6d536/steal/steal.py#L399

I should be doing a root operation instead of a logarithm. 

What I am guessing is that the error only occurs when the user cannot afford the number of levels they originally entered in, and the code inside the `if` block is executed. I will push a fix soon.
